#!python
import asyncio as aio
from pathlib import Path
from argparse import ArgumentParser, RawTextHelpFormatter
from configparser import ConfigParser

from serobot.web.serobot_server import SerobotServer


def parse_arguments():
    argument_parser = ArgumentParser(formatter_class=RawTextHelpFormatter)

    argument_parser.add_argument(
        'config_file', nargs='?', type=Path,
        help=('A configuration file listing the other arguments as\n'
              '\n'
              '[config]\n'
              'auth_file = /path/to/auth/file\n'
              'ssl_certfile = /path/to/ssl/certfile\n'
              'ssl_keyfile = /path/to/ssl/keyfile'))
    argument_parser.add_argument(
        '-a', '--auth-file', type=Path,
        help=('A file that lists the authorized usernames and\n'
              'passwords. The file must contain sections of the form\n'
              '\n'
              '[myusername]\n'
              'password = mypassword'))
    argument_parser.add_argument(
        '-c', '--ssl-certfile', type=Path, help='Path to a certificate file for SSL, .pem')
    argument_parser.add_argument(
        '-k', '--ssl-keyfile', type=Path, help='Path to a key file for SSL, .pem')

    arguments, _ = argument_parser.parse_known_args()
    arguments = vars(arguments)

    # Update the values in arguments with the contents
    # of a config file, if given.
    config_path = arguments.pop('config_file')
    if config_path is not None:
        config = ConfigParser()
        config.read(config_path)
        # At the moment all variables in the .conf file are path-like,
        # so convert them blindly to Path objects.
        arguments.update({
            name: Path(value) for (name, value) in config.items('config')})

    return arguments


if __name__ == '__main__':
    server = SerobotServer(**parse_arguments())
    aio.run(server.start())
